source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'MYKeyboard' do
    pod 'SnapKit'#, '~> 3.2.0'
    pod 'FMDB', '~> 2.7.5'
end

target 'MiYKeyboard' do
    pod 'SnapKit'#, '~> 3.2.0'
    pod 'FMDB', '~> 2.7.5'
    
end
